plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.newmyapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.newmyapp"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation platform('com.google.firebase:firebase-bom:33.12.0')
    implementation 'com.google.firebase:firebase-auth:21.0.5'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-firestore:24.10.1'
    implementation 'com.google.firebase:firebase-storage:20.0.0'
    implementation 'com.google.android.gms:play-services-auth:20.4.0'

    //pet adoption and find missing pet
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'

    //navigation bar
    implementation 'com.google.android.material:material:1.9.0'  // Use the latest version
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0' // Ensure CoordinatorLayout dependency is included
    implementation 'androidx.appcompat:appcompat:1.2.0'







}